testsite/mainapp/urls.py
from django.urls import path, include
from django.contrib.auth.views import LogoutView

from . import views
from .views import *

urlpatterns = [
    path('', home_page, name='home'),
    # path('product/', product_list, name='product_list'),
    path('create/', post_create, name='post_create'),
    path('detail/', post_detail, name='post_detail'),
    path('detail_old/<str:Legal_Entity>-<str:property>-<str:Camera_Name>/', post_detail_old, name='post_detail_old'),
    path('create_property/', create_property, name='create_property'),
    path('create_Legal_Entity/', create_Legal_Entity, name='create_Legal_Entity'),

    path('posts/', all_posts, name='all_posts'),
    path('posts/calculator/', calculator, name='calculator'),

    # path('<str:legal_Entity>/<str:property>/<str:Camera_Name>/', post_detail, name='post_detail'),
    path('detail/<str:Legal_Entity>-<str:property>-<str:Camera_Name>/', post_detail, name='post_detail'),

    path('property_list_ajax/', property_list_ajax, name='property_list_ajax'),



    path('detail/<str:Legal_Entity>-<str:property>-<str:Camera_Name>/edit/', post_edit, name='post_edit'),
    path('detail/<str:Legal_Entity>-<str:property>-<str:Camera_Name>/edit0/', post_edit0, name='post_edit0'),
    path('detail/<str:Legal_Entity>-<str:property>-<str:Camera_Name>/edit1/', post_edit1, name='post_edit1'),
    path('detail/<str:Legal_Entity>-<str:property>-<str:Camera_Name>/edit2/', post_edit2, name='post_edit2'),
    path('detail/<str:Legal_Entity>-<str:property>-<str:Camera_Name>/edit3/', post_edit3, name='post_edit3'),
    path('detail/<str:Legal_Entity>-<str:property>-<str:Camera_Name>/edit4/', post_edit4, name='post_edit4'),
    path('detail/<str:Legal_Entity>-<str:property>-<str:Camera_Name>/delete/', post_delete, name='post_delete'),



    path('detail_old/<str:Legal_Entity>-<str:property>-<str:Camera_Name>/settings0/', post_edit_Settings0, name='post_edit_Settings0'),
    path('detail_old/<str:Legal_Entity>-<str:property>-<str:Camera_Name>/settings1/', post_edit_Settings1, name='post_edit_Settings1'),
    path('detail_old/<str:Legal_Entity>-<str:property>-<str:Camera_Name>/settings2/', post_edit_Settings2, name='post_edit_Settings2'),
    path('detail_old/<str:Legal_Entity>-<str:property>-<str:Camera_Name>/settings3/', post_edit_Settings3, name='post_edit_Settings3'),
    path('detail_old/<str:Legal_Entity>-<str:property>-<str:Camera_Name>/settings4/', post_edit_Settings4, name='post_edit_Settings4'),
    path('detail_old/<str:Legal_Entity>-<str:property>-<str:Camera_Name>/settings5/', post_edit_Settings5, name='post_edit_Settings5'),
    path('detail_old/<str:Legal_Entity>-<str:property>-<str:Camera_Name>/settings6/', post_edit_Settings6, name='post_edit_Settings6'),
    path('detail_old/<str:Legal_Entity>-<str:property>-<str:Camera_Name>/settings7/', post_edit_Settings7, name='post_edit_Settings7'),
    path('detail_old/<str:Legal_Entity>-<str:property>-<str:Camera_Name>/settings8/', post_edit_Settings8, name='post_edit_Settings8'),
    path('detail_old/<str:Legal_Entity>-<str:property>-<str:Camera_Name>/settings9/', post_edit_Settings9, name='post_edit_Settings9'),
    path('detail_old/<str:Legal_Entity>-<str:property>-<str:Camera_Name>/settings10/', post_edit_Settings10, name='post_edit_Settings10'),

    path('detail_old/<str:Legal_Entity>-<str:property>-<str:Camera_Name>/', post_detail_old, name='post_detail_old'),
    # path('detail_old/<str:Legal_Entity>-<str:property>-<str:Camera_Name>/delete/', post_delete, name='post_delete'),
    # path('<str:title>/delete1/', post_delete1, name='post_delete1'),
    # path('<str:title>/delete2/', post_delete2, name='post_delete2'),
    path('posts/search/', search, name='search'),
    # path('logout/', LogoutView.as_view(), name='logout'),
    # path('list/', book_author_list, name='book_author_list'),



    # path('update/', update_post, name='update_post'),
]

testsite/testsite/urls.py
from django.contrib import admin
from django.urls import path, include
from mainapp.views import *
from django.contrib.auth.views import LogoutView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/login/', login_view, name='login'),
    path('', include('mainapp.urls')),
    # path('logout/', LogoutView.as_view(), name='logout'),
    path('accounts/logout/',auth_views.LogoutView.as_view(), name='logout'),
# ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

testsite/mainapp/models.py
from django.db import models

def upload_location(instance, filename):
    return f'{instance.id}, {filename}'

class Product(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    price = models.DecimalField(max_digits=6, decimal_places=2)


class Post(models.Model):

    # title = models.CharField(max_length=500,blank=True, null=True )
    #Create post
    Legal_Entity = models.CharField(max_length=500,)
    property = models.CharField(max_length=500,)
    Camera_Name = models.CharField(max_length=500,)
    Property_Name = models.CharField(max_length=500,blank=True, null=True )

    # Town_Postcode = models.CharField(max_length=500,blank=True, null=True )
    Company = models.CharField(max_length=500,blank=True, null=True )

    town = models.CharField(max_length=500, )
    postcode = models.CharField(max_length=500, )
    phone_number = models.CharField(max_length=500, )
    # Test_admin = models.CharField(max_length=500, unique=True)
    confirm_video_recorded = models.BooleanField(default=False)

    door_photo = models.ImageField(upload_to='images/', blank=True, null=True)
    aspect_of_door = models.CharField(blank=True, null=True, max_length=500)
    light_meter_reading_inside = models.CharField(blank=True, null=True, max_length=500)
    # калькулятор
    # camera_calculator_info = models.CharField(blank=True, null=True, max_length=500)

    internet_speed_test = models.ImageField(upload_to='images/', blank=True, null=True)


    # Hardware Information:




    camera_serial = models.CharField(max_length=50,blank=True, null=True)
    face_box_id = models.CharField(max_length=50, blank=True, null=True)
    kasa_login_id = models.CharField(max_length=50, blank=True, null=True)
    SWITCH_MODELS = (
        ('HIK', 'HIK'),
        ('TPLink', 'TPLink'),

    )

    switch_make_and_model = models.CharField(choices=SWITCH_MODELS, max_length=50, blank=True, null=True)

    router_serial = models.CharField(max_length=50, blank=True, null=True)

    PHONE_MODELS = (
        ('Iphone 8 ', 'Iphone 8 '),
        ('Iphone 10', 'Iphone 10'),

    )

    phone_models = models.CharField(choices=PHONE_MODELS, max_length=50, blank=True, null=True)
    phone_serial = models.CharField(max_length=50, blank=True, null=True)
    phone_sim = models.CharField(max_length=50, blank=True, null=True)

    Photo_of_camera = models.ImageField(upload_to='images/', blank=True, null=True)
    Photo_of_router = models.ImageField(upload_to='images/', blank=True, null=True)
    Photo_of_switch = models.ImageField(upload_to='images/', blank=True, null=True)

    # Camera Setup:

    Generated_Camera_name = models.CharField(max_length=50, blank=True, null=True)
    firmware_up_to_date = models.BooleanField(default=False)
    sd_card_installed = models.BooleanField(default=False)
    settings_optimized = models.BooleanField(default=False)
    face_size_screenshot = models.ImageField(upload_to='images/', blank=True, null=True)
    min_face_size = models.IntegerField(blank=True, null=True)
    notes = models.TextField(blank=True, null=True)

    # Site Audit information:

    door_sticker_photo = models.ImageField(upload_to='images/', blank=True, null=True)
    set_up_pc_and_app = models.BooleanField(default=False)
    train_staff = models.BooleanField(default=False)
    customer_sme_name = models.CharField(max_length=100, blank=True, null=True)
    leave_fw_install_crib_sheet_photo = models.ImageField(upload_to='images/', blank=True, null=True)




    # Install on site
    # Installer_Company = models.CharField(max_length=500,blank=True, null=True )
    # Installer_email = models.CharField(max_length=500,blank=True, null=True )
    # Install_date = models.CharField(max_length=500, blank=True, null=True)
    Door_entrance_width = models.CharField(max_length=500, blank=True, null=True)
    Distance_from_door= models.CharField(max_length=500, blank=True, null=True)
    Height = models.CharField(max_length=500, blank=True, null=True)
    Angle_to_face_Degrees = models.CharField(max_length=500, blank=True, null=True)
    Pixels_per_face = models.CharField(max_length=500, blank=True, null=True)
    # Video_on_teams = models.CharField(max_length=500, blank=True, null=True)
    Facebox_id = models.CharField(max_length=500,blank=True, null=True )
    Kasa_login = models.CharField(max_length=500,blank=True, null=True )
    Router_Serial_No = models.CharField(max_length=500, blank=True, null=True)
    Phone_Model = models.CharField(max_length=500, blank=True, null=True)
    Phone_Serial_No = models.CharField(max_length=500, blank=True, null=True)
    Lightmeter_reading_at_entrance = models.CharField(max_length=500, blank=True, null=True)


    Test_camera_set = models.CharField(max_length=500, blank=True, null=True)

    # new
    Lumen_or_candle = models.CharField(max_length=500, blank=True, null=True)
    Aspect = models.CharField(max_length=500, blank=True, null=True)
    Door_type = models.CharField(max_length=500, blank=True, null=True)
    Describe_aspect = models.CharField(max_length=500, blank=True, null=True)


#    INSTALER ON SITE
#     Vivotek_cam_updated = models.CharField(max_length=500, blank=True, null=True)

    # Auto_Camera_Name = models.CharField(max_length=500,blank=True, null=True )
    # Input_Camera_Name_Into_Camera = models.CharField(max_length=500, blank=True, null=True)


    Camera_time = models.CharField(max_length=500,blank=True, null=True )
    Bitrate = models.CharField(max_length=500,blank=True, null=True )
    Video_quality = models.CharField(max_length=500,blank=True, null=True )
    # Zoom_to_door_and_preset= models.CharField(max_length=500, blank=True, null=True)

    #Final checks
    # Horiz_mfs_from_detection = models.CharField(max_length=500, blank=True, null=True)
    # Horiz_mfs_from_safr = models.CharField(max_length=500, blank=True, null=True)
    # Are_faces_detected = models.CharField(max_length=500, blank=True, null=True)
    # Are_alerts_working = models.CharField(max_length=500, blank=True, null=True)
    # Name_of_store_manager = models.CharField(max_length=500, blank=True, null=True)
    # Is_web_login = models.CharField(max_length=500, blank=True, null=True)
    User_login_app = models.CharField(max_length=500, blank=True, null=True)
    # User_trained = models.CharField(max_length=500, blank=True, null=True)
    Name_of_fw_user = models.CharField(max_length=500, blank=True, null=True)


    #Safr info
    Safr_feed_name = models.CharField(max_length=500, blank=True, null=True)
    Safr_feed_site = models.CharField(max_length=500, blank=True, null=True)
    Safr_feed_source = models.CharField(max_length=500, blank=True, null=True)
    Rtsp_adress= models.CharField(max_length=500, blank=True, null=True)
    Safr_mfs = models.CharField(max_length=500, blank=True, null=True)
    Safr_min_backoff = models.CharField(max_length=500, blank=True, null=True)
    Safr_tracker_failed = models.CharField(max_length=500, blank=True, null=True)
    Safr_min_pose_quality = models.CharField(max_length=500, blank=True, null=True)



    # Photos
    # Camera_Position_Image = models.ImageField(upload_to='images/',
    #                                           null=True, blank=True,)
    # Facebox_Switch_location_image = models.ImageField(upload_to='images/',
    #                            null=True, blank=True,)
    # Router_location_image = models.ImageField(upload_to='images/',
    #                            null=True, blank=True,)
    # Image_of_signage_in_doorway_image = models.ImageField(upload_to='images/',
    #                            null=True, blank=True,)

    # 'mainapp/static/mainapp/images/'
    #Day param
    Camera_serial_no = models.CharField(max_length=500, blank=True, null=True)
    Name_of_profile_day = models.CharField(max_length=500, blank=True, null=True)
    Time_profile_day = models.CharField(max_length=500, blank=True, null=True)
    White_balance_day = models.CharField(max_length=500, blank=True, null=True)
    Brightness_day = models.CharField(max_length=500, blank=True, null=True)
    Saturation_day = models.CharField(max_length=500, blank=True, null=True)
    Sharpness_day = models.CharField(max_length=500, blank=True, null=True)
    Digital_noise_day = models.CharField(max_length=500, blank=True, null=True)
    Exposure_level_day = models.CharField(max_length=500, blank=True, null=True)
    Exposure_mode_day = models.CharField(max_length=500, blank=True, null=True)
    Iris_day = models.CharField(max_length=500, blank=True, null=True)
    Exposure_time_day = models.CharField(max_length=500, blank=True, null=True)
    Exposure_gain_day = models.CharField(max_length=500, blank=True, null=True)
    Wdr_pro_day = models.CharField(max_length=500, blank=True, null=True)
    wdr_level_day = models.CharField(max_length=500, blank=True, null=True)

    Name_of_profile_night = models.CharField(max_length=500, blank=True, null=True)
    Time_profile_night = models.CharField(max_length=500, blank=True, null=True)
    White_balance_night = models.CharField(max_length=500, blank=True, null=True)
    Brightness_night = models.CharField(max_length=500, blank=True, null=True)
    Saturation_night = models.CharField(max_length=500, blank=True, null=True)
    Sharpness_night = models.CharField(max_length=500, blank=True, null=True)
    Digital_noise_night = models.CharField(max_length=500, blank=True, null=True)
    Exposure_level_night = models.CharField(max_length=500, blank=True, null=True)
    Exposure_mode_night = models.CharField(max_length=500, blank=True, null=True)
    Iris_night = models.CharField(max_length=500, blank=True, null=True)
    Exposure_time_night = models.CharField(max_length=500, blank=True, null=True)
    Exposure_gain_night = models.CharField(max_length=500, blank=True, null=True)
    Wdr_pro_night = models.CharField(max_length=500, blank=True, null=True)

testsite/mainapp/templates/mainapp/all_posts.html
{%  load static %}
<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
<link rel="stylesheet" href="{% static 'mainapp/css/main.css' %}">
{% block navbar %}


{% endblock %}

<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'all_posts' %}">Camera</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'create_Legal_Entity' %}">Legal Entity</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'create_property' %}">Create property</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'post_create' %}">Create Camera</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'calculator' %}">Calculator</a>
        </li>

       <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}?next={% url 'login' %}">Logout</a>
        </li>

      </ul>

    </div>
  </div>
</nav>


<h4></h4>

<form class="d-flex" role="search", action="{% url 'search' %}",>
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>












<div class="card" >

    {% for post in posts %}

  <div class="card-body" >
    <h5 class="card-title">{{post.Legal_Entity}}-{{post.property}}-{{post.Camera_Name}}</h5>
      <p>{{ post.pub_date }}</p>
    <a href="{% url 'post_detail' Legal_Entity=post.Legal_Entity property=post.property Camera_Name=post.Camera_Name %}" class="btn btn-primary">Open</a>
    <a href="{% url 'post_detail_old' Legal_Entity=post.Legal_Entity property=post.property Camera_Name=post.Camera_Name %}" class="btn btn-primary">Open old</a>
  </div>

    <td><hr></td>

    {% endfor %}

</div>

testsite/mainapp/templates/mainapp/home_page.html
{% extends 'mainapp/base.html' %}


<!--  <main>-->
<!--    <div class="container">-->
<!--      <div class="row">-->
<!--        <div class="col-md-6">-->
<!--          <h2>Пошук</h2>-->
<!--          <form>-->
<!--            <div class="input-group mb-3">-->
<!--              <input type="text" class="form-control" placeholder="Пошук" aria-label="Пошук" aria-describedby="basic-addon2">-->
<!--              <div class="input-group-append">-->
<!--                <button class="btn btn-outline-secondary" type="button">Пошук</button>-->
<!--              </div>-->
<!--            </div>-->
<!--          </form>-->
<!--        </div>-->
<!--      </div>-->
<!--    </div>-->
<!--  </main>-->
<!--  <footer>-->
<!--    <nav class="navbar navbar-expand-lg navbar-light bg-light">-->
<!--      <ul class="navbar-nav ml-auto">-->
<!--        <li class="nav-item">-->
<!--          <button type="button" class="btn btn-danger" id="logoutBtn" style="display: none;">Вийти</button>-->
<!--        </li>-->
<!--      </ul>-->
<!--    </nav>-->
<!--  </footer>-->




{#<html>#}
{#<head>#}
{#	<title>Home</title>#}
{#</head>#}
{#<body>#}
{#	<h1>Home</h1>#}
{##}
{#	<button><a href="posts/">Camera</a></button>#}
{##}
{##}
{#</body>#}
{#</html>#}
<a href="{% url 'logout' %}">Logout</a>

testsite/mainapp/templates/mainapp/post_create.html
{%  load static %}
<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
<link rel="stylesheet" href="{% static 'mainapp/css/main.css' %}">







<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'all_posts' %}">Camera</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'create_Legal_Entity' %}">Legal Entity</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'create_property' %}">Create property</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'post_create' %}">Create Camera</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'calculator' %}">Calculator</a>
        </li>

       <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}?next={% url 'login' %}">Logout</a>
        </li>

      </ul>

    </div>
  </div>
</nav>



<center>
<div class="container">
  <h1>Create Camera</h1>

<form method="post" enctype="multipart/form-data" >
    {% csrf_token %}
    {{ form.as_p }}


    <button type="submit">Create</button>
  </form>
</div>
</center>



<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
  $(document).ready(function() {
    $("#id_Legal_Entity").change(function() {
      var Legal_Entity = $(this).val();
      $.ajax({
        url: "{% url 'property_list_ajax' %}",
        data: {'Legal_Entity': Legal_Entity},
        dataType: 'json',
        success: function(data) {
          $("#id_property").empty();
          $.each(data.properties, function(i, property) {
            $("#id_property").append($('<option>').val(property.id).text(property.property));
          });
        }
      });
    });
  });
</script>

testsite/mainapp/templates/mainapp/post_edit.html
{%  load static %}
<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
<link rel="stylesheet" href="{% static 'mainapp/css/main.css' %}">
{% block navbar %}

<!--<header>-->
<!--    <nav class="navbar navbar-expand-lg navbar-light bg-light">-->
<!--&lt;!&ndash;      <a class="navbar-brand" href="#">Моя сторінка</a>&ndash;&gt;-->
<!--      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">-->
<!--        <span class="navbar-toggler-icon"></span>-->
<!--      </button>-->
<!--      <div class="collapse navbar-collapse" id="navbarNav">-->
<!--        <ul class="navbar-nav">-->
<!--          <li class="nav-item active">-->
<!--            <a class="nav-link" href="/">Home </a>-->
<!--          </li>-->
<!--          <li class="nav-item">-->
<!--            <a class="nav-link" href="{% url 'all_posts' %}">Posts</a>-->
<!--          </li>-->
<!--          <li class="nav-item">-->
<!--            <a class="nav-link" href="{% url 'post_create' %}">Post Create</a>-->
<!--          </li>-->
<!--          <li class="nav-item">-->
<!--            <a class="nav-link" href="{% url 'calculator' %}">Calculator</a>-->
<!--          </li>-->
<!--          <li class="nav-item">-->
<!--            <a class="nav-link" href="{% url 'logout' %}">Logout</a>-->
<!--          </li>-->
<!--        </ul>-->
<!--        <ul class="navbar-nav ml-auto">-->
<!--		</ul>-->
<!--      </div>-->
<!--    </nav>-->
<!--  </header>-->




<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'all_posts' %}">Camera</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'create_Legal_Entity' %}">Legal Entity</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'create_property' %}">Create property</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'post_create' %}">Create Camera</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'calculator' %}">Calculator</a>
        </li>

       <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}?next={% url 'login' %}">Logout</a>
        </li>

      </ul>

    </div>
  </div>
</nav>







{% endblock %}

<center>
<h1>Edit FWADMIN</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save changes</button>
  </form>
</center>



<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
  $(document).ready(function() {
    $("#id_Legal_Entity").change(function() {
      var Legal_Entity = $(this).val();
      $.ajax({
        url: "{% url 'property_list_ajax' %}",
        data: {'Legal_Entity': Legal_Entity},
        dataType: 'json',
        success: function(data) {
          $("#id_property").empty();
          $.each(data.properties, function(i, property) {
            $("#id_property").append($('<option>').val(property.id).text(property.property));
          });
        }
      });
    });
  });
</script>